### PR TITLE
Create formula.rb

### PR DESCRIPTION
**Pull request by gingerbeardman**
We need to check this.

### CODE REVIEW

**Comment by RJVB** [comment]
IMHO this has nothing to do with the afsctool code, and I don't really like adding things I won't be maintaining (let alone use). I use MacPorts myself (for a reason, let's leave it at that) but the Portfile for my afsctool version is hosted in a dedicated repository. It may sound strange, but I prefer to "stay neutral" and not favour one packaging effort over another, in here at least.

**Comment by gingerbeardman** [comment]
That's fair enough. I'll see if it's OK for me to host just this tap file.

**Comment by grischard** [comment]
@gingerbeardman I was wondering if you'd hosted the tap yourself in the end? I can't find it in your repos.

**Comment by gingerbeardman** [comment]
Nope, sorry. 

There was some drama at Homebrew regarding this fork, so you'd have to take it up with them.

**Comment by grischard** [comment]
Oh dear, that sounds bad. What a pity. Thank you very much for trying.

**Comment by gingerbeardman** [comment]
It's very easy to build yourself, so I recommend doing that. It's not the type of software that has multiple major updates.

**Pull request closed without merging**
